[phases.setup]
nixPkgs = ['python311', 'unixODBC']

[phases.install]
cmds = [
  'pip install -r requirements.txt'
]

[phases.build]
cmds = ['echo "No build phase"']

[start]
cmd = 'gunicorn --bind 0.0.0.0:$PORT app:app'